[project]
name = "local-livestream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.0",
    "qwen-asr>=0.0.6",
    "sounddevice>=0.5.2",
    "torch>=2.8.0",
]
